openapi: 3.0.0
info:
  title: Система проведения стажировок
  version: 1.0.0
tags:
  - name: Система стажировок
    description: API системы стажировок
paths:
  /api/usersEmployed:
    post:
      tags:
        - Система стажировок
      summary: Отправка списка стажеров
      operationId: userEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lastName
                - firstName
                - middleName
                - dateBirth
                - gender
                - phone
                - mail
                - directionInternship
                - position
              properties:
                lastName:
                  type: string
                  description: Фамилия
                firstName:
                  type: string
                  description: Имя
                middleName:
                  type: string
                  description: Отчество
                dateBirth:
                  type: string
                  description: Дата рождения
                gender:
                  type: string
                  description: Пол
                phone:
                  type: string
                  description: Телефон
                mail:
                  type: string
                  description: Эектронная почта
                directionInternship:
                  type: string
                  description: Направление стажировки
                position:
                  type: string
                  description: Должность
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                    description: Данные приняты на обработку
        '400':
          description: Некорректный запрос
        '403':
          description: Доступ запрещен
        '500':
          description: Запрос не был выполнен из-за непредвиденной проблемы с сервером
        '503':
          description: Время ожидания истекло
 
components:
  securitySchemes:
    HumanResources:
      type: http
      scheme: bearer
      bearerFormat: JWT